default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ai_chat
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: ai_chat_test
  password: <%= ENV["DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: ai_chat
  password: <%= ENV["DATABASE_PASSWORD"] %>
